/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Demo */

#ifndef _Included_Demo
#define _Included_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Demo
 * Method:    showInCpp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Demo_showInCpp
  (JNIEnv *, jclass);

/*
 * Class:     Demo
 * Method:    showInCpp2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Demo_showInCpp2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
